#!/bin/bash
# Команди для тестування на Render з правильним хостом

echo "=== КОМАНДИ ДЛЯ ВИКОНАННЯ НА RENDER ==="
echo ""
echo "1. Отримати реальний хост Render:"
echo "   echo \$RENDER_EXTERNAL_HOSTNAME"
echo "   # або"
echo "   hostname"
echo ""

echo "2. Перевірити ALLOWED_HOSTS:"
echo "   python manage.py shell -c \"from django.conf import settings; print('ALLOWED_HOSTS:', settings.ALLOWED_HOSTS)\""
echo ""

echo "3. Тест context processor з правильним хостом (замініть YOUR_HOST на реальний):"
echo "   python manage.py shell -c \""
echo "   from django.test import RequestFactory"
echo "   from apps.core.context_processors import seo_context"
echo "   rf = RequestFactory()"
echo "   request = rf.get('/')"
echo "   request.META['HTTP_HOST'] = 'speakup-zc5s.onrender.com'  # ЗАМІНІТЬ НА ВАШ ХОСТ"
echo "   request.META['SERVER_NAME'] = 'speakup-zc5s.onrender.com'"
echo "   request.META['SERVER_PORT'] = '443'"
echo "   request.META['HTTP_X_FORWARDED_PROTO'] = 'https'"
echo "   try:"
echo "       result = seo_context(request)"
echo "       print('✅ OK:', 'default_og_image' in result)"
echo "   except Exception as e:"
echo "       print('❌ ERROR:', type(e).__name__, ':', str(e))"
echo "       import traceback"
echo "       traceback.print_exc()"
echo "   \""
echo ""

echo "4. Перевірити реальний запит (симуляція):"
echo "   python manage.py shell -c \""
echo "   from django.test import Client"
echo "   client = Client(HTTP_HOST='speakup-zc5s.onrender.com')  # ЗАМІНІТЬ"
echo "   try:"
echo "       response = client.get('/')"
echo "       print('Status:', response.status_code)"
echo "   except Exception as e:"
echo "       print('ERROR:', type(e).__name__, ':', str(e))"
echo "       import traceback"
echo "       traceback.print_exc()"
echo "   \""
echo ""

echo "5. Найважливіше - перевірити логи на реальній помилці:"
echo "   # Відкрийте Render Dashboard → Logs"
echo "   # Знайдіть останній Traceback перед помилкою 500"
echo "   # Скопіюйте повний Traceback"
echo ""

echo "=== ПРОБЛЕМА МОЖЕ БУТИ В ==="
echo "1. request.build_absolute_uri() викликає DisallowedHost"
echo "2. Потрібно додати try-except в context_processors.py"
echo ""


