# Generated by Django 5.2 on 2025-12-24 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug_uk', models.SlugField(max_length=200, unique=True)),
                ('slug_ru', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('title_uk', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('content_uk', models.TextField()),
                ('content_ru', models.TextField(blank=True)),
                ('meta_description_uk', models.TextField(max_length=500)),
                ('meta_description_ru', models.TextField(blank=True, max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/images/')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('old_url_uk', models.CharField(blank=True, max_length=500)),
                ('old_url_ru', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['slug_uk', 'is_published'], name='core_newsar_slug_uk_68958e_idx'), models.Index(fields=['slug_ru', 'is_published'], name='core_newsar_slug_ru_089885_idx'), models.Index(fields=['published_at', 'is_published'], name='core_newsar_publish_52e4af_idx')],
            },
        ),
    ]
