# Generated by Django 4.2.8 on 2025-12-24 11:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(verbose_name='Число')),
                ('label_uk', models.CharField(max_length=100, verbose_name='Назва (UK)')),
                ('label_ru', models.CharField(blank=True, max_length=100, verbose_name='Назва (RU)')),
                ('suffix', models.CharField(blank=True, help_text='Наприклад: +, %', max_length=10, verbose_name='Суфікс')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Досягнення',
                'verbose_name_plural': 'Досягнення',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_uk', models.CharField(max_length=100, verbose_name='Заголовок (UK)')),
                ('title_ru', models.CharField(blank=True, max_length=100, verbose_name='Заголовок (RU)')),
                ('front_text_uk', models.TextField(verbose_name='Текст спереду (UK)')),
                ('front_text_ru', models.TextField(blank=True, verbose_name='Текст спереду (RU)')),
                ('back_text_uk', models.TextField(verbose_name='Текст ззаду (UK)')),
                ('back_text_ru', models.TextField(blank=True, verbose_name='Текст ззаду (RU)')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='advantages/', verbose_name='Іконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Номер має бути в форматі +380XXXXXXXXX', regex='^\\+380\\d{9}$')], verbose_name='Телефон')),
                ('prefers_messenger', models.BooleanField(default=False, verbose_name='Консультація в переписці')),
                ('messenger_choice', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('telegram', 'Telegram')], max_length=20, verbose_name='Месенджер')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('utm_content', models.CharField(blank=True, max_length=100, verbose_name='UTM Content')),
                ('utm_term', models.CharField(blank=True, max_length=100, verbose_name='UTM Term')),
                ('fbclid', models.CharField(blank=True, max_length=200, verbose_name='Facebook Click ID')),
                ('gclid', models.CharField(blank=True, max_length=200, verbose_name='Google Click ID')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Referrer')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
            ],
            options={
                'verbose_name': 'Заявка на консультацію',
                'verbose_name_plural': 'Заявки на консультацію',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=100, verbose_name='Назва (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Назва (RU)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категорія курсів',
                'verbose_name_plural': 'Категорії курсів',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_uk', models.CharField(max_length=200, verbose_name='Питання (UK)')),
                ('question_ru', models.CharField(blank=True, max_length=200, verbose_name='Питання (RU)')),
                ('answer_uk', models.TextField(verbose_name='Відповідь (UK)')),
                ('answer_ru', models.TextField(blank=True, verbose_name='Відповідь (RU)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('text', models.TextField(max_length=500, verbose_name='Текст відгуку')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Від 1 до 5', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубліковано')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерації')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_testimonials', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_uk', models.CharField(max_length=200, verbose_name='Назва (UK)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Назва (RU)')),
                ('short_desc_uk', models.TextField(max_length=300, verbose_name='Короткий опис (UK)')),
                ('short_desc_ru', models.TextField(blank=True, max_length=300, verbose_name='Короткий опис (RU)')),
                ('detail_content_uk', models.TextField(verbose_name='Детальний контент (UK)')),
                ('detail_content_ru', models.TextField(blank=True, verbose_name='Детальний контент (RU)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активний')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.coursecategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
