# Generated by Django 5.2 on 2025-12-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_achievement_advantage_consultationrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='back_text_ru',
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='back_text_uk',
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='front_text_ru',
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='front_text_uk',
        ),
        migrations.AddField(
            model_name='advantage',
            name='footer_text_ru',
            field=models.TextField(blank=True, verbose_name='Текст футера (RU)'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='footer_text_uk',
            field=models.TextField(blank=True, verbose_name='Текст футера (UK)'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='footer_title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок футера (RU)'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='footer_title_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок футера (UK)'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Підзаголовок (RU)'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Підзаголовок (UK)'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='tag_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Тег (RU)'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='tag_uk',
            field=models.CharField(blank=True, max_length=150, verbose_name='Тег (UK)'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title_uk',
            field=models.CharField(max_length=200, verbose_name='Заголовок (UK)'),
        ),
        migrations.CreateModel(
            name='AdvantageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_emoji', models.CharField(blank=True, max_length=20, verbose_name='Емодзі іконки')),
                ('title_uk', models.CharField(blank=True, max_length=100, verbose_name='Заголовок (UK)')),
                ('title_ru', models.CharField(blank=True, max_length=100, verbose_name='Заголовок (RU)')),
                ('text_uk', models.TextField(verbose_name='Текст (UK)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Текст (RU)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('advantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.advantage', verbose_name='Перевага')),
            ],
            options={
                'verbose_name': 'Пункт переваги',
                'verbose_name_plural': 'Пункти переваг',
                'ordering': ['order', 'id'],
            },
        ),
    ]
