# Generated by Django 5.2 on 2025-12-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_advantage_back_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='messenger_choice',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], max_length=20, verbose_name='Месенджер'),
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_uk', models.CharField(help_text='Наприклад: +38 (093) 170-78-67', max_length=20, verbose_name='Телефон (UA)')),
                ('phone_international', models.CharField(blank=True, help_text='Наприклад: +48 (459) 567-884', max_length=20, verbose_name='Міжнародний телефон')),
                ('schedule_weekdays_uk', models.CharField(help_text='Наприклад: Пн-Пт: 10:00-21:30', max_length=50, verbose_name='Графік роботи будні (UK)')),
                ('schedule_weekdays_ru', models.CharField(blank=True, help_text='Наприклад: Пн-Пт: 10:00-21:30', max_length=50, verbose_name='Графік роботи будні (RU)')),
                ('schedule_weekend_uk', models.CharField(help_text='Наприклад: Сб: 11:00-15:00', max_length=50, verbose_name='Графік роботи вихідні (UK)')),
                ('schedule_weekend_ru', models.CharField(blank=True, help_text='Наприклад: Сб: 11:00-15:00', max_length=50, verbose_name='Графік роботи вихідні (RU)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Тільки один активний запис може існувати', verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Контактна інформація',
                'verbose_name_plural': 'Контактна інформація',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_contact_info')],
            },
        ),
    ]
