# Generated by Django 5.2 on 2026-01-07 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_consultationrequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Введіть коректний український номер телефону', regex='^\\+380\\d{9}$')], verbose_name='Телефон'),
        ),
    ]
