# Generated by Django 5.2 on 2026-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_runninglinetext_from_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='referrer',
            field=models.URLField(blank=True, help_text='Сторінка, з якої прийшов користувач', max_length=500, verbose_name='Referrer'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='utm_campaign',
            field=models.CharField(blank=True, help_text='Назва кампанії', max_length=100, verbose_name='UTM Campaign'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='utm_content',
            field=models.CharField(blank=True, help_text='Контент оголошення', max_length=100, verbose_name='UTM Content'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='utm_medium',
            field=models.CharField(blank=True, help_text='Канал (cpc, organic, social)', max_length=100, verbose_name='UTM Medium'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='utm_source',
            field=models.CharField(blank=True, help_text='Джерело трафіку (google, facebook, instagram)', max_length=100, verbose_name='UTM Source'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='utm_term',
            field=models.CharField(blank=True, help_text='Ключове слово', max_length=100, verbose_name='UTM Term'),
        ),
    ]
