# Generated by Django 5.2 on 2025-12-24 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunningLineText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Текст бігучої стрічки',
                'verbose_name_plural': 'Тексти бігучої стрічки',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TrialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Номер має бути в форматі +380XXXXXXXXX', regex='^\\+380\\d{9}$')], verbose_name='Телефон')),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('fbclid', models.CharField(blank=True, max_length=200, verbose_name='Facebook Click ID')),
                ('gclid', models.CharField(blank=True, max_length=200, verbose_name='Google Click ID')),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('test_status', models.CharField(choices=[('not_started', 'Не розпочато'), ('skipped', 'Пропущено'), ('completed', 'Завершено')], default='not_started', max_length=20)),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заявка на пробний урок',
                'verbose_name_plural': 'Заявки на пробні уроки',
                'ordering': ['-created_at'],
            },
        ),
    ]
