# Generated by Django 5.2 on 2026-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_name_email_to_consultation'),
        ('leads', '0006_add_consultationrequest_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка footer',
                'verbose_name_plural': 'Заявки footer',
                'proxy': True,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'indexes': [],
                'constraints': [],
            },
            bases=('core.consultationrequest',),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email відправлено'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата нотифікації'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='referrer',
            field=models.URLField(blank=True, help_text='Сторінка, з якої прийшов користувач', max_length=500, verbose_name='Referrer'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='telegram_sent',
            field=models.BooleanField(default=False, verbose_name='Telegram відправлено'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='test_results',
            field=models.JSONField(blank=True, null=True, verbose_name='Результати тесту'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='test_status',
            field=models.CharField(choices=[('not_started', 'Не розпочато'), ('skipped', 'Пропущено'), ('completed', 'Завершено')], default='not_started', max_length=20, verbose_name='Статус тесту'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='utm_campaign',
            field=models.CharField(blank=True, help_text='Назва кампанії', max_length=100, verbose_name='UTM Campaign'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='utm_content',
            field=models.CharField(blank=True, help_text='Контент оголошення', max_length=100, verbose_name='UTM Content'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='utm_medium',
            field=models.CharField(blank=True, help_text='Канал (cpc, organic, social)', max_length=100, verbose_name='UTM Medium'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='utm_source',
            field=models.CharField(blank=True, help_text='Джерело трафіку (google, facebook, instagram)', max_length=100, verbose_name='UTM Source'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='utm_term',
            field=models.CharField(blank=True, help_text='Ключове слово', max_length=100, verbose_name='UTM Term'),
        ),
    ]
